### ISSUE TITLE
fail to delete when used with path.join on windows

### ISSUE THREAD

**Issue by ramezghaly** [sindresorhus/del#105]
var pathTodelete = path.join('platforms', platform ,'app');
del.sync(pathToDelete]); // will do nothing even if the path does not have patterns

var pathTodelete = path.posix.join('platforms', platform ,'app');
del.sync(pathToDelete]);//works fine

del version 5.0.0
node version 10.16.2

**Comment by chrisblossom** [comment]
> You can no longer pass in paths with backward-slashes. If you need to construct a glob pattern, use path.posix.join() instead of path.join(). You can use slash to transform backward-slash paths to forward-slash paths.

This is expected. Please read https://github.com/sindresorhus/del/releases

See also #100.
