### ISSUE TITLE
Merge del-cli

### ISSUE THREAD

**Issue by chrisblossom** [sindresorhus/del#110]
Would you accept a PR that merges [`del-cli`](https://github.com/sindresorhus/del-cli) into this library? I often find myself having to require both `del` and `del-cli` as a dependency and think it would be a lot nicer to have this in one package.

**Comment by sindresorhus** [comment]
No, it's split for some good reasons:
- Users of `del` should not have to pay for CLI-related dependencies.
- From experience, many people missed the CLI part when I had them in one module.
- The readme gets noisy when it has to document both the API and CLI part.
- Very few use both at the same time.

See https://github.com/sindresorhus/ama/issues/17 for more.
