### ISSUE TITLE
migration guide 4->5

### ISSUE THREAD

**Issue by oprogramador** [sindresorhus/del#112]
Could you publish a migration guide telling what's needed to update when upgrading from `del@4` to `del@5`?

I use it as a dev dependency and the build passed so I hope everything is OK but I'd like to be sure.

**Comment by sindresorhus** [comment]
It's in the usual place: https://github.com/sindresorhus/del/releases/tag/v5.0.0

**Comment by oprogramador** [comment]
thanks
