### ISSUE TITLE
Windows 10 error missing default windows icons

### ISSUE THREAD

**Issue by isuruwijesundara** [sindresorhus/del#114]
Some default windows icon are not showing in my pc
Windows 10 
Version 1903
What i do this..please help me. 
I attached some images. 
Is it font missing??

![15685048197551105628460](https://user-images.githubusercontent.com/46338388/64914883-411d5700-d778-11e9-90d2-198fc16ecc49.jpg)
![1568504873202-1677652901](https://user-images.githubusercontent.com/46338388/64914884-424e8400-d778-11e9-9ca6-f85018f73658.jpg)
![1568504910941-618074977](https://user-images.githubusercontent.com/46338388/64914891-65793380-d778-11e9-9114-d1a90cbbd089.jpg)

**Comment by sindresorhus** [comment]
This is not the place to ask for Windows support.
