### ISSUE TITLE
Delete only subdirectories (empty & full both)

### ISSUE THREAD

**Issue by deadcoder0904** [sindresorhus/del#115]
As confirmed [here](https://github.com/sindresorhus/del/issues/76#issuecomment-527181867), empty directories are not deleted.

My use case is to delete only subfolders.

My tree structure is 

```
dist
├── a/
├── b/
├── a.md
└── b.txt
```

And I want to delete `dist/a` & `dist/b` using `del-cli` so I installed it globally & tried

```bash
$ del 'dist/**/*'
```

But it, unfortunately, deleted everything inside `dist/`. I just want to delete all subfolders & keep all the files inside `dist` untouched.

**Comment by deadcoder0904** [comment]
I found the answer on [StackOverflow](https://stackoverflow.com/a/58057440/6141587). This works -

```bash
$ del dist/*/
```

**Comment by sindresorhus** [comment]
Maybe you want to submit a tip about that to the readme?

**Comment by deadcoder0904** [comment]
submitted PR https://github.com/sindresorhus/del/pull/116
