### ISSUE TITLE
del is no longer deleting files after updating to v5

### ISSUE THREAD

**Issue by dippas** [sindresorhus/del#117]
I have this gulpfile (simplified for this use case), that I've been using for awhile 

```
//--------- Include references
const gulp = require('gulp'),
    del = require('del'),
    assetsPath = '../Project.Web/Assets/';
// more references here

//--------- Define Paths
const paths = {
    views: {
        index: 'dist/'
    }
}
// more paths here 

//--------- Clean files
function clean(done) {
    del.sync([(`${paths.views.index.dest}**/`, `${assetsPath}**/`)], {
        force: true
    });
    done();
}
// more functions here

//--------- Create tasks 
gulp.task('clean', clean)
// more tasks here

//--------- Dist folders
gulp.task('build', gulp.series('clean', gulp.parallel(otherNotRelevantTasksHere)

//---------Default task
gulp.task('default', gulp.series('build'))
```
Since I've updated  the `del` package from 4.1.1 to 5.0.0 (or any newer version) the function itself runs but it doesn't delete the folders

![image](https://user-images.githubusercontent.com/10220287/66136266-16922180-e5f3-11e9-9c6b-9349155fba4e.png)

I've read a few issues such as #93  or #94  or even #100 , but I couldn't find a solution for this. 

Things I've tried:

- make the function async, by using `async function`
- using `return` and removing `sync` form `del`
- even `path.josix.join()` but I'm not even using backward-slashes, although I'm in a windows environment. 

I would appreciate any help on this because I'd like to keep this package in this project (without to reverse to 4.1.1)

**Comment by dippas** [comment]
@sindresorhus  I know you are very busy with the PRs and stuff but can you please take a look at this? I would really appreciate it :)

**Comment by kevva** [comment]
There's a PR with an explanation how to do this https://github.com/sindresorhus/del/pull/116.

Try using one `*` instead:

```js
del.sync([(`${paths.views.index.dest}*/`, `${assetsPath}*/`)], {
	force: true
});
```

**Comment by dippas** [comment]
@kevva  thank you :) I have seen that but didn't associate with my  issue.

just a quick note, I had to delete the `()` inside the square brackets `[]`, otherwise it would only delete the last path.

so finally I ended up with this:

```
del.sync([`${paths.views.index.dest}*`, `${assetsPath}*`], {
    force: true
});
```
