### ISSUE TITLE
slowness on require - lazy initialization proposal

### ISSUE THREAD

**Issue by Loksly** [sindresorhus/del#118]
Hi!

I just want to share with you something I have noticed.
First of all, thanks for your time developing and sharing your library.
It's simple to use and does what it says.

I use your library with gulp and as I guess so many people does the same way.
I have a task like this one:

gulpfile.js:

```js
const del = require('del');
/* other stuff */
function clean() {
    return del([path.resolve(__dirname, 'dist'), path.resolve(__dirname, 'built')]);
}
exports.clean = clean;
/* other stuff */
```

I've noticed that my gulp tasks were slow to start, then I started to change to `require` functions only when they are needed (let's call it _lazy initialization_), so the code for this task changed to:

```js
/* other stuff */
function clean() {
    const del = require('del');

    return del([path.resolve(__dirname, 'dist'), path.resolve(__dirname, 'built')]);
}
exports.clean = clean;
/* other stuff */
```

I measured the time that the gulp command processes the gulpfile using `console.time` and `console.timeEnd`, and this small change saved me from 66ms to 3ms.

Example of the beginning of my gulpfile.json, where I measure the time needed to start running tasks:

```js
console.time('load');

const { series, parallel, src } = require('gulp');

const gulp = require('gulp'),
	path = require('path'),
	Q = require('q'),
 	fs = require('fs'),
// del = require('del'),
 	gulpconfig = JSON.parse(fs.readFileSync(path.resolve(__dirname, './gulpconfig.json'), 'utf8'));

console.timeEnd('load');
```

You might not consider this time too much, but you might consider doing the same in your library (_lazy initialization_), so you save time to a lot of people, when they import your library but not really need it.

**Comment by sindresorhus** [comment]
Sorry, I'm not interested in complicating the code here with lazy initialization. However, you could use https://github.com/sindresorhus/import-lazy to easily lazy import `del` and other modules.
