### ISSUE TITLE
Del plugin conflicts with latest VSCode

### ISSUE THREAD

**Issue by Alecto** [sindresorhus/del#120]
Recently I noticed that when working with javascript in visual studio code, when I press ctrl + space, no popup help are displayed, only "loading ...".

The node_modules folder is located in the root directory relative to the project folder.
Experiments with the problem have led to the fact that if I remove the del plugin from node_modules folder, the hints in VSCode start working correctly. If I install the del plugin - the hints stop working.

**Comment by alkorlos** [comment]
I have same problem on win 10. On last mac OS all fine.
On win 10 this problem with versions over 4.1.0, with 4.1.0 works correctly.

**Comment by alkorlos** [comment]
I have same problem on win 10. On last mac OS all fine.
On win 10 this problem with versions over 4.1.0, with 4.1.0 works correctly.
node v12.14.1

**Comment by sindresorhus** [comment]
You should report an issue on VSCode. Even if it turns out `del` is the cause of something, VSCode should have shown a more clear error about it.

**Comment by Alecto** [comment]
so vscode works correctly if I remove the del plugin. Also, I noticed that the problem occurs if node_modules is on par with the vscode folder.

**Comment by alkorlos** [comment]
In Visual Studio Code 1.42.1 all fine.
