### ISSUE TITLE
{dryRun: true} not working with Sync mode

### ISSUE THREAD

**Issue by pjebs** [sindresorhus/del#122]

**Comment by sindresorhus** [comment]
We have a test for it: https://github.com/sindresorhus/del/blob/4acd96267f3bfb6b06de7968ba97063586de7466/test.js#L99-L110

**Comment by pjebs** [comment]
I needed to `force: true` too. In dryRun, why is that required?

**Comment by sindresorhus** [comment]
I assume it was because the path was outside the `cwd`. A dry-run should work like the real operation.
