### ISSUE TITLE
Cannot delete dirs containing files with invalid UTF8 sequences in their name

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/del#124]
On Linux or Windows (not macOS as it throws `EILSEQ` on `writeFileSync`), do:

````bash
mkdir test
cd test
node -p 'fs.writeFileSync(Buffer.from([0x78, 0xf6, 0x6c, 0x78]), "test")'
cd ..
node -p 'require("del").sync("test")' # fails
node -p 'fs.rmdirSync("test", {recursive: true})' # works
````

Error seems to come from rimraf which I think erronously attempts UTF8 decoding:

````
Error: ENOTEMPTY: directory not empty, rmdir '/tmp/test'
    at Object.rmdirSync (fs.js:865:3)
    at rmkidsSync (/tmp/node_modules/rimraf/rimraf.js:349:27)
    at rmdirSync (/tmp/node_modules/rimraf/rimraf.js:329:7)
    at Function.rimrafSync [as sync] (/tmp/node_modules/rimraf/rimraf.js:301:9)
    at /tmp/node_modules/del/index.js:112:11
    at Array.map (<anonymous>)
    at AsyncFunction.module.exports.sync (/tmp/node_modules/del/index.js:104:29)
````

**Comment by sindresorhus** [comment]
Seems more like a Node.js big. It should consistently throw that error on all platforms, not just macOS.

**Comment by silverwind** [comment]
I suspect the `EILSEQ` is either an APFS limitation or a libuv bug.

**Comment by silverwind** [comment]
Regarding the deletion bug I think best course of action is to use `fs.rmdir` instead of `rimraf`, but to my knowledge, it's only available on node 12.16 or higher.

**Comment by sindresorhus** [comment]
> But to my knowledge recursive is only available on node 12.16 or higher.

We could check for that and at least do the right thing for those versions.

**Comment by silverwind** [comment]
I'd prefer a backport of https://github.com/nodejs/node/pull/29168 to v10.

**Comment by silverwind** [comment]
I think it's probably better I workaround this in my module because:

- This modules doe state support for Buffers and it seems geared towards glob strings.
- Fixing the non-UTF8 would require version detection and it would only work on Node 12.
- `fs.rmdir` does not support glob so it would not get rid of dependencies.

I guess Buffer support could be revisited once 12 is the minimum version.

**Comment by silverwind** [comment]
Edited above. I think the root cause may be somewhere in `globby` or its dependencies. To really fix it, those modules would have to avoid passing around paths as string and use Buffers exclusively because `Buffer.from([0x78, 0xf6, 0x6c, 0x78])` can not be represented as an UTF-8 string.
