### ISSUE TITLE
Plugin is not working with Electron App

### ISSUE THREAD

**Issue by sadashivm** [sindresorhus/del#132]
Hello, I'm using this npm package with an electron app with React JS. I'm getting the below error.

![image](https://user-images.githubusercontent.com/10355473/106789379-310d5c80-6678-11eb-8c0b-3c718eb2d475.png)

Here is the my code,
![image](https://user-images.githubusercontent.com/10355473/106789646-8f3a3f80-6678-11eb-934f-51829f288421.png)

Can you please tell me the reason why it is not working? 
Have I missed anything?

**Comment by sindresorhus** [comment]
`del` is a Node.js module. You're using it in the renderer. It should be used in the Electron main process. I suggest asking Electron questions on the Electron support forums.
