### ISSUE TITLE
Weird problem in the npm page

### ISSUE THREAD

**Issue by TomEpsilon** [sindresorhus/del#137]
<img width="909" alt="image" src="https://user-images.githubusercontent.com/81517212/155666957-6fe9433f-c7c8-4ff0-9730-6428afae7c3e.png">

_Evil._

**Comment by sindresorhus** [comment]
It's fixed locally: https://github.com/sindresorhus/del/commit/72007d759fdad5a1547012c24fe9d8b9768a7cb9

I don't do updates just for readme typos.
