### ISSUE TITLE
Protocol 'node:' not supported

### ISSUE THREAD

**Issue by KubaLorenc** [sindresorhus/del#153]
I'm getting 
Error [ERR_INVALID_PROTOCOL]: Protocol 'node:' not supported. Expected 'file:'
    Object.<anonymous> (node_modules/del/index.js:1)
    Generator.next (<anonymous>)
    Object.newLoader [as .js] (node_modules/pirates/lib/index.js:141:7)

I'm trying to dynamically import del 
`import plugin from '@start/plugin';

export default patterns =>
  plugin('clean', () => async () => {
    return import('del').then(deleteAsync => deleteAsync(patterns));
  });`

Is it correct way to import it dynamically and if so can you look into why am I getting this error?

**Comment by sindresorhus** [comment]
This is not a problem with this package. I would recommend asking on `@start` issue tracker.
