### ISSUE TITLE
Unable to require/import this module into gulp

### ISSUE THREAD

**Issue by MiguelDebruyne** [sindresorhus/del#159]
I've been splitting my hairs trying to make this work after I've been away for some years, coming back and rewriting/updating my gulpfile.

I import all packages via `require`. However for **del** this doesn't work anymore.

`
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/del/index.js from gulpfile.js not supported. Instead change the require of index.js in gulpfile.js to a dynamic import() which is available in all CommonJS modules.
`

When I then try
```js
import del from 'del';
```
or
```js
import {del} from 'del';
```

I get the following

```js
SyntaxError: Cannot use import statement outside a module
```

After a lot searching I read that you need to add `"type": "module"` to the package.json, which I don't like, but ok.

Then when I try both the previous stated imports again I get this

`SyntaxError: The requested module 'del' does not provide an export named 'del'`

What am I missing here? Every example I see of gulp using **del** uses `require`

**Comment by sindresorhus** [comment]
From the readme:

```js
import {deleteAsync} from 'del';
```
