### ISSUE TITLE
del.sync doesn't work with options not defined

### ISSUE THREAD

**Issue by whitecolor** [sindresorhus/del#18]
`sync` is not supplied with (empty) object `options` there is an error
```
 TypeError: Object.keys called on non-object
```

**Comment by sindresorhus** [comment]
Works fine: https://github.com/sindresorhus/del/commit/b15779d36131612dfc206135bac34913376bfa78

https://twitter.com/sindresorhus/status/579306280495357953

**Comment by whitecolor** [comment]
hm, for me it didn't on windows  with pattern like `[some/path/dir/*]`
