### ISSUE TITLE
Is ** supposed to match the base directory?

### ISSUE THREAD

**Issue by superlukas** [sindresorhus/del#21]
`del('foo/bar/**')` should *not* remove `foo/bar`, right?
`del('foo/bar/*')` and `del('foo/bar/**/*')` work as expected.

Maybe I just don't understand how the globstar option really works but my shell (zsh) doesn't touch the base directory.

**Comment by stramel** [comment]
@superlukas I belive that statement is incorrect. `del('foo/bar/**')` *should* remove `foo/bar`. If you look at the documentation linked [here](https://github.com/isaacs/node-glob#glob-primer) it states:

> `**` If a "globstar" is alone in a path portion, then it matches zero or more directories and subdirectories searching for matches. It does not crawl symlinked directories.

So the key there is zero or more directories, so it will match `foo/bar` as one of the directories. So if you are wanting to keep that directory you would be wanting `del('foo/bar/**/*');`

@sindresorhus Please correct me if I am wrong!

**Comment by superlukas** [comment]
@stramel I've read the same quote; that's why I ended up opening the issue in the first place.

I couldn't find anything "official" on the topic; all I know is that zsh had globstars first and they don't match `bar` (I don't know what bash does; the quote comes from their docs IIRC). Maybe this is supposed to be in line with how git expands globs: `foo/bar/**` inside a gitignore file doesn't let you `add foo/bar`. Maybe I'm missing something, I'm not sure. I don't have any globstar options set in my zsh config.

It's all the same to me, really. I've decided to always use `**/*` and I didn't lose any files either. A note in the docs might spare others some pain though.

/cc @isaacs

**Comment by isaacs** [comment]
I don't know if this answers your question, but here's the intended behavior of node-glob:

```
$ tree
.
├── b/
│   ├── x/
│   │   └── file.txt
│   └── y/
│       └── file.txt
└── c/
    ├── x/
    │   └── file.txt
    └── y/
        └── file.txt

6 directories, 4 files

$ for i in **; do echo $i; done
b
b/x
b/x/file.txt
b/y
b/y/file.txt
c
c/x
c/x/file.txt
c/y
c/y/file.txt

$ for i in **/; do echo $i; done
b/
b/x/
b/y/
c/
c/x/
c/y/

$ for i in ./**/; do echo $i; done
./
./b/
./b/x/
./b/y/
./c/
./c/x/
./c/y/

$ for i in b/**; do echo $i; done
b/
b/x
b/x/file.txt
b/y
b/y/file.txt

$ for i in b/*/**; do echo $i; done
b/x
b/x/file.txt
b/y
b/y/file.txt

$ echo $BASH_VERSION
4.3.30(6)-release
```

So, to answer the OP question: yes, `foo/bar/**` does indeed match `foo/bar`.  But `foo/bar/*/**` does not.

**Comment by superlukas** [comment]
@isaacs "Intended" is the word I wanted to hear. Thanks :)
