### ISSUE TITLE
Is options.cwd official?

### ISSUE THREAD

**Issue by goloroden** [sindresorhus/del#23]
I have seen that there is an [`options.cwd`](https://github.com/sindresorhus/del/blob/c5fefd60664f7417045e26f8ea88a8482ac33654/index.js#L45) option that allows you to set the current working directory when running `del`. This property is extremly useful, but unfortunately it is not documented.

So, my question is, am I safe to use it (in other words, it's just the documentation missing) or is it considered private and I should stick away from it?

**Comment by sindresorhus** [comment]
It's documented, just not here. It's part of the node-glob docs. We just have `cwd` code in here to play nice with that option.

https://github.com/sindresorhus/del#options
