### ISSUE TITLE
Returning a promise

### ISSUE THREAD

**Issue by andrewsuzuki** [sindresorhus/del#25]
When using multiple calls to del in a Gulp task, a callback or promise return is needed. It would be nice to use del in this case without a callback pyramid or hacky counter. Is there any reason del() shouldn't return a promise?

**Comment by sindresorhus** [comment]
I haven't really started using promises yet. I don't like the idea of having to use a promise polyfill for every little module I create. I'm waiting out for the native support.

For now you can easily use https://github.com/petkaantonov/bluebird/blob/master/API.md#promisefromnodefunction-resolver---promise or something though.
