### ISSUE TITLE
Open to Promise API?

### ISSUE THREAD

**Issue by wbinnssmith** [sindresorhus/del#28]
I'm wondering if you'd be open to me implementing a Promise API in addition to taking the callback. Could be useful for those using gulp (where this module seems to be frequently used as opposed to rimraf) who want a nice readable API. Would you take such a patch?

**Comment by sindresorhus** [comment]
Sure, but I would prefer going all in and only expose a promise. Should use [`pinkie-promise`](https://github.com/floatdrop/pinkie-promise). PR welcome.
