### ISSUE TITLE
Negating a pattern is not working

### ISSUE THREAD

**Issue by citricsquid** [sindresorhus/del#3]
```
.
├── assets
│   ├── .gitkeep
│   ├── rev-manifest.json
│   ├── style-2ccbb519.css
```

I'm auto compiling my less and using [gulp-rev](https://github.com/sindresorhus/gulp-rev) for revisioning. I have a clean:css task defined like so:

```
gulp.task('clean:css', function (cb) {
    del(['public/assets/**', '!public/assets/.gitkeep'], cb);
});
```

When running the **clean:css** task everything in the ```public/assets``` directory is removed including ```.gitkeep```, I expect ```.gitkeep``` to remain in place. I have replaced ```.gitkeep``` with ```example.txt``` to rule out problems with empty files and the problem persists (example.txt contained "example").

Have I missed something obvious, if not is there something I can do to debug this? I'm using ubuntu 14.04 (through Vagrant). Gulp is at version 3.8.7, npm is 1.3.10 and del is 0.1.1.

I followed [this recipe](https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md).

Thank you!

**Comment by stramel** [comment]
I am having issues excluding a entire sub-folder.

```
dist
|--src
|  |--main
|  |  |--webapp // Want to delete anything in here except WEB-INF
|  |  |  |--assets 
|  |  |  |--fonts
|  |  |  |--WEB-INF // Keep this folder
|  |  |  |  |--web.xml
|  |  |  |  |--weblogic.xml 
|  |--pom.xml
```

```js
del(['dist/**/*', '!dist/**/WEB-INF/**/*'])
```

**Comment by sindresorhus** [comment]
@stramel What is the output of:

```js
del(['dist/**/*'])
```

and

```js
del(['dist/**/WEB-INF/**/*'])
```

?

**Comment by stramel** [comment]
@sindresorhus 

```js
del(['dist/**/*']) 
// Results in empty dist folder
```
and
```js
del(['dist/**/WEB-INF/**/*']) 
// Results in empty 'WEB-INF' folder and the rest of the structure intact
```

**Comment by sindresorhus** [comment]
Hmm, what's the output of this:

Install [`globby`](https://github.com/sindresorhus/globby) first.

```js
var globby = require('globby');

console.log(globby.sync(['dist/**/*']));
console.log();
console.log(globby.sync(['dist/**/WEB-INF/**/*']));
```

**Comment by stramel** [comment]
Okay, so it results in:

```js
gulp.task('clean', function (done) {
  console.log(globby.sync(['dist/**/*']));
  console.log();
  console.log(globby.sync(['dist/**/WEB-INF/**/*']));
  done();
});
```

```console
$ gulp clean
[
  'dist/src',
  'dist/src/main',
  'dist/src/main/webapp',
  'dist/src/main/webapp/WEB-INF',
  'dist/src/main/webapp/WEB-INF/web.xml',
  'dist/src/main/webapp/WEB-INF/weblogic.xml',
  'dist/src/main/webapp/assets',
  'dist/src/main/webapp/fonts',
  'dist/src/main/webapp/scripts',
  'dist/src/main/webapp/styles',
  'dist/src/pom.xml',
  'dist/target'
 ]

[
  'dist/src/main/webapp/WEB-INF/web.xml',
  'dist/src/main/webapp/WEB-INF/weblogic.xml'
]
```

Using

```js
console.log(globby.sync(['dist/**/WEB-INF/**']));
```

results in 

```console
$ gulp clean
[
  'dist/src/main/webapp/WEB-INF',
  'dist/src/main/webapp/WEB-INF/web.xml',
  'dist/src/main/webapp/WEB-INF/weblogic.xml'
]
```

Using

```js
console.log(globby.sync(['dist/**/*', '!dist/**/WEB-INF', '!dist/**/WEB-INF/**]));
```

results in 

```console
$ gulp clean
[
  'dist/src',
  'dist/src/main',
  'dist/src/main/webapp',
  'dist/src/main/webapp/assets',
  'dist/src/main/webapp/fonts',
  'dist/src/main/webapp/scripts',
  'dist/src/main/webapp/styles',
  'dist/src/pom.xml',
  'dist/target'
 ]
```
yet, when running through `del`:

```js
$.del(['dist/**/*', '!dist/**/WEB-INF', '!dist/**/WEB-INF/**]);
```
results in an empty dist folder.

**Comment by stramel** [comment]
Closest  I have come is using the follow:

```js
$.del(['dist/**', '!dist/**/WEB-INF/**'], {nodir: true});
// But this leaves the unwanted folders
```

**Comment by sebastian-rightshift** [comment]
Thanks @Sparticuz, your solution worked for me.

**Comment by iest** [comment]
Ran into this as well. @Sparticuz 's solution worked for me.

**Comment by derMart** [comment]
I ran into the same problem.
@Sparticuz's solution ( https://github.com/sindresorhus/del/issues/3#issuecomment-64001316 ) 
only works, if the negate pattern adresses the next hierarchy level, won't work for problems like https://github.com/sindresorhus/del/issues/3#issuecomment-69382833

@stramel: Thats exactly what I also think. Negate patterns should follow path to root and remove directory matches. Is this a glob or a del issue?

**Comment by Ferdaszewski** [comment]
Any solution? I ran across this when trying to delete all files and folders, excluding one, in a gulp task:
```javascript
del(['dist/**/*', '!dist/scripts/bundle.js']);
/// deletes all files and folders including 'dist/scripts/bundle.js'
```

**Comment by stramel** [comment]
@Ferdaszewski You currently could do:

```js
// Properly excludes dist/scripts/bundle.js
del(['dist/**/*', '!dist/scripts/', '!dist/scripts/bundle.js']); 

// or to exclude everything in scripts
del(['dist/**/*', '!dist/scripts/', '!dist/scripts/**']);
```

Those are untested but should work. you can quickly test these using either of these snippets:

```js
var globby = require('globby');
console.log(globby.sync(<INSERT_GLOBS_HERE>));
```

```js
var gulp = require('gulp');
var debug = require('gulp-debug');

gulp.task('debug:glob', function () {
  var pattern = <INSERT_GLOBS_HERE>;

  return gulp.src(pattern, { read: false })
    .pipe(debug());
});
```

```

**Comment by Ferdaszewski** [comment]
@stramel Thank you for the response and help! Unfortunately this does not work as expected:
```javascript
del(['dist/**/*', '!dist/scripts/', '!dist/scripts/bundle.js']);
// deletes all files and folders including dist/scripts/ and dist/scripts/bundle.js
```
However, your gulp debug snippet did work as expected, so this is the workaround I'm using:
```javascript
var del = require('del');
var gulp = require('gulp');
var vinylPaths = require('vinyl-paths');

gulp.task('clean', function() {
  var pattern = ['dist/**/*', '!dist/scripts/', '!dist/scripts/bundle.js'];
  return gulp.src(pattern, {read: false})
    .pipe(vinylPaths(del));
});

**Comment by zsoltszabo** [comment]
Its amazing that this repo is still so bad quality with all this popularity. I read the whole thread, though you might expect after thousands of downloads you would not need to do that for a simple task like this.
```javascript
  del(['../build/**/*','!../node_modules{,/**}']
```
I want to delete a damn folder except for a folder in it. Simple heh?

I tried the above with every possible combination of options {force:true, dot: true,nodir: true}...,
single stars, double stars, hybrid whatever. Still files from node_modules are wiped. Prolly instead of experimenting I could have written a working repo within the same time frame.

**Comment by arthurvr** [comment]
> Its amazing that this repo is still so bad quality with all this popularity.




> Prolly instead of experimenting I could have written a working repo within the same time frame.

Please stop complaining. This is free, open source software and everybody is free to submit a PR with a fix :)

**Comment by arthurvr** [comment]
Even a pull request with failing unit tests would already be a big help.

**Comment by Ferdaszewski** [comment]
@arthurvr added a failing unit test and sent pull request #24.

**Comment by atwellpub** [comment]
I found luck with this, if it helps anyone

 return del([
        '../leads/**/*',
        '!../leads/svn{,/**}'
    ], {force: true});

**Comment by dave-dm** [comment]
one thing I realized is that you need to exclude each folder in the path, a well as inside the folders, example:
```javascript
del([
    `${BASE_FOLDER}/**/*`,
    `!${BASE_FOLDER}/folderA{,/folderB{,/**/*}}`
  ]
```
which would be the same as
```javascript
del([
    `${BASE_FOLDER}/**/*`,
    `!${BASE_FOLDER}/folderA`,
    `!${BASE_FOLDER}/folderA/folderB`,
    `!${BASE_FOLDER}/folderA/folderB/**/*`
  ]
