### ISSUE TITLE
Option to remove symlink instead of cleaning the folder

### ISSUE THREAD

**Issue by gera2ld** [sindresorhus/del#30]
I tried to remove a symlink to a directory but found that the whole folder is cleared. Should there be an option for this?

**Comment by sindresorhus** [comment]
It shouldn't follow symlinks by default unless you set the [`follow`](https://github.com/isaacs/node-glob#options) option. I just tried and it correctly deleted the symlink, not the symlinked directory. Can you submit a failing test?

**Comment by gera2ld** [comment]
Sorry, it's my fault to have built a junction instead of symlink to a directory. After changing the link to a symlink, it works perfectly.
