### ISSUE TITLE
del.sync is still async

### ISSUE THREAD

**Issue by robertbaker** [sindresorhus/del#32]
I'm using del with gulp and 

gulp.task('del', function(done) {
    return del.sync(path);
// also tried return done;
});

Gulp task doesn't return

**Comment by wbinnssmith** [comment]
If you accept a callback in your gulp task you're expected to call it. If you do anything asynchronous you'll need to either accept a callback and call it or return either a stream or a promise to end the task correctly.

Try removing "done" from your task's arguments. You can also `return del(path)` now that `del`'s async implementation returns a promise!

**Comment by eugenekgn** [comment]
So let me understand this del.sync(files) is still async call so if you're waiting for it to finish in order to start another process as part of gulp it would still run in parallel with a task that depends on it? 

And the solutiong for it is to return del(path)? what happened to del(path, callback) which worked so nicely in 1.1.1?

**Comment by TrySound** [comment]
@eugenekgn This is correct.
```
gulp.task('compile', function (done) {
  del.sync('path');
  done();
});
gulp.task('compile', function (done) {
  return del('path');
});
```

**Comment by eugenekgn** [comment]
what is 

```
done()
```

it looks very hakish.

**Comment by TrySound** [comment]
@eugenekgn It's not hakish. It's callback. Calling it you inform gulp about task ending. Returning a promise or stream is alternative. But we not always have promise or stream.

In del@1 the right way was
```
gulp.task('compile', function (done) {
  del('path', done);
});
```

But now we can just return a promise form del. And you don't need sync functions. Async is faster.

**Comment by eugenekgn** [comment]
I know that async is faster but if my compile process waits for something to be deleted via .less -> .css compilation... it makes sense to do it in sync.

**Comment by TrySound** [comment]
@eugenekgn Nope, it doesn't matter. Gulp tasks are async functions since gulp@4, so you should always think about async. Everything inside gulp tasks should be async.

**Comment by TrySound** [comment]
@eugenekgn Async doesn't mean parallel, if you thought about it.

**Comment by eugenekgn** [comment]
#TrySound, you're correct, I meant to say one gets kicked of after another... but thanks for clarifying it...
