### ISSUE TITLE
Using iojs 3.3.0 and latest del along with gulp - no joy 

### ISSUE THREAD

**Issue by dstroot** [sindresorhus/del#33]
Using this simple pattern for a long time now in gulp:
```
var del = require('del');

gulp.task('clean', function(cb) {
    del(['output'], cb);
});

/**
 * Build Task
 *   - Build all the things...
 */

gulp.task('build', function (cb) {
  runSequence(
    'clean',                     // first clean
    ['lint', 'jscs'],            // then lint and jscs
    ['styles', 'scripts'],       // Then styles and scripts
    ['test'],                    // test it!
    cb);
});
```

Updated `del` yesterday when the new version came out and now my build stops at `clean`:

```
❯ gulp
[05:07:15] Using gulpfile ~/Code/bootstrap4-starter-kit/gulpfile.js
[05:07:15] Starting 'build'...
[05:07:15] Starting 'clean'...
```

No errors thrown...

Anyone have any ideas?

**Comment by sindresorhus** [comment]
It's a major version bump for a reason. Major meaning breaking. Always look at the changes before upgrading a major version: https://github.com/sindresorhus/del/compare/v1.2.1...v2.0.1 Specifically: https://github.com/sindresorhus/del/commit/6589c52f289a1f8e94652f6a2cad9413cdee26dc

https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md

**Comment by dstroot** [comment]
Sindre - sorry to bother you. I did try to find out what was different - honest!  For anyone else looking at this the cb is not longer required:

```
gulp.task('clean', function () {
  return del(paths.clean);
});
```

**Comment by Nirazul** [comment]
I have to agree with @dstroot. Naturally I looked at the main github page and incorporated `del().then();` with the callback workflow.
Since gulp is probably one of the most frequent use cases of your plugin, it wouldn't hurt to make an example with a return stream.
