### ISSUE TITLE
delete files from network share

### ISSUE THREAD

**Issue by jzp74** [sindresorhus/del#35]
I was using grunt quite happely when I stumbled upon an issue in removing files from a network location with grunt-contrib-clean

So I just tried del in combination with gulp but ended having (at first glance) the same issue. I'm new to gulp so maybe i'm missing something. This is my extremely simple gulpfile.js

    var gulp = require('gulp'),
        del = require('del');

    gulp.task('clean', function(cb) {
        del(['//some/network/location/*'], { force: true }, cb)
    });

    gulp.task('default', function() {
        gulp.start('clean');
    });

Running gulp gives me no errors but the files in //some/network/location are still there. Is this unsupported use, misuse or a bug?

I'm running gulp on a Windows 8 machine from within Git bash. Shared location is on my synology NAS.

**Comment by TrySound** [comment]
@jzp74 Read documentation, please. New api uses promises instead of callback.

**Comment by jzp74** [comment]
@TrySound Thanks for your reply. You mean this documentation: https://github.com/gulpjs/gulp/blob/master/docs/API.md?
Not sure I understand how that would change my gulp clean task. Can you elaborate a bit more?

**Comment by TrySound** [comment]
@jzp74 This documentation
https://github.com/sindresorhus/del

**Comment by TrySound** [comment]
@jzp74 Instead of passing callback as the last argument you can just return result of del function. gulp tasks accept streams and promises.

**Comment by jzp74** [comment]
@TrySound Thanks!

So I tried this with a normal directory

    gulp.task('clean', function(cb) {
        del(['dist/css/*.css'], { force: true });
        cb();
    });

Works perfectly. I then tried this (basically the same) with the shared location

    gulp.task('clean', function(cb) {
        del(['//some/network/location/dist/css/*.css'], { force: true });
        cb();
    });

Doesn't work and renders no errors or warning. This should work right?

Then tried this to see if something is perhaps wrong wiith my shared location.

    gulp.task('clean', function (cb) {
        exec('rm -fr //some/network/location/dist/css/*', function (err, stdout, stderr) {
        console.log(stdout);
        console.log(stderr);
        cb(err);
        });
    })

Works perfectly. It looks like del doesn't work with shared locations. Am I still doing something wrong? Is there something else you would like me to test?

**Comment by TrySound** [comment]
@jzp74 Do not use callback here. You call cb before del end.
```js
gulp.task('clean', function() {
    return del(['dist/css/*.css'], { force: true });
});
```

**Comment by TrySound** [comment]
@jzp74 I don't know about shared location.
/cc @sindresorhus

**Comment by jzp74** [comment]
Removed the callback for both the local delete as for the shared location delete. Same results: local delete works, shared location delete doesn't

**Comment by landed1** [comment]
I am here too ..issues on shared drive requires the force option...here is my code
gulp.task('clean',function(){
  return gulp.src(DEST)
      .pipe(vinylPaths(del(DEST, { force: true })));
});

I was using vinylPaths as I wanted to do this on a stream of ONLY changed files

**Comment by schnittstabil** [comment]
ATM, `glob` does not support UNC globs, see https://github.com/isaacs/node-glob/pull/74 and https://github.com/isaacs/node-glob/pull/74. Thus, this also applies to `del`.

However there's a workaround:
1. use [glob's `root` option](https://github.com/isaacs/node-glob#options): *The place where __patterns starting with `/`__ will be mounted onto.*
2. use a glob __pattern starting with `/`__.
3. use [del's `force` option](https://github.com/sindresorhus/del#force): *Allow deleting the current working directory __and outside__.*

### Example:
```js
del('/dist/css/*.css', {
  root: '//ComputerName/SharedFolder',
  force: true,
});
```

#### Notes:
1. globbing *ComputerNames* is not possible – Windows processes these in a different way
2. globbing *SharedFolders* is not possible – Windows processes these in a different way
3. Promises fail silently, i. e. to output error message one need to catch it:
  ```js
  del(…).then(console.log).catch(console.error)
  ```

4. Of course, `gulp` outputs errors, but only if one return the Promise:
  ```js
  gulp.task('clean', function() {
    return del(…);
  });
  ```

This should answer all questions.
