### ISSUE TITLE
Why hidden files are not deleted ?

### ISSUE THREAD

**Issue by ImpactSeo** [sindresorhus/del#38]
Hello, I'm using del in as a gulp task : 
```javascript
gulp.task('clean', function() {
    var deferred = Q.defer();
    del(output + '**/*', function() {
        deferred.resolve();
    });
    return deferred.promise;
});
```
but when checking my output folder .htaccess fil is still there : is my syntax correct to also delete hidden files ? Thanks for your help !

**Comment by kevva** [comment]
Set `dot: true` in the options.

**Comment by nolimitdev** [comment]
Why `doc` option is not documented here https://github.com/sindresorhus/del please?
