### ISSUE TITLE
Gulp task problem with del

### ISSUE THREAD

**Issue by ramasilveyra** [sindresorhus/del#42]
Sincerely, I'm not so sure if this error is from this package or gulp. But you can help me.
When I call my gulp task clean
```javascript
gulp.task('clean', cb => {
  del(['.tmp', 'dist/*', '!dist/.git'], {dot: true}).then(cb);
});
```
I get this:
```
[01:28:16] Requiring external module babel-core/register
[01:30:33] Using gulpfile d:\www\web-starter-kit\gulpfile.babel.js
[01:30:33] Starting 'clean'...
[01:30:34] 'clean' errored after 325 ms
[01:30:34] Error
    at formatError (C:\Users\ramasilveyra\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Users\ramasilveyra\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
    at emitOne (events.js:77:13)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (d:\www\web-starter-kit\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
    at d:\www\web-starter-kit\node_modules\gulp\node_modules\orchestrator\index.js:275:23
    at finish (d:\www\web-starter-kit\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (d:\www\web-starter-kit\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
```

Maybe a problem with the promise?

**Comment by sindresorhus** [comment]
Which `del` version are you on?

**Comment by ramasilveyra** [comment]
@sindresorhus Last version, 2.0.2.

**Comment by sindresorhus** [comment]
See the release notes for using the API properly. Your way will not propegate errors.

**Comment by ramasilveyra** [comment]
Thanks, I solved in this way:
```javascript
gulp.task('clean', () => del(['.tmp', 'dist/*', '!dist/.git'], {dot: true}));
````
Like: https://github.com/gulpjs/gulp/commits/master/docs/recipes/delete-files-folder.md

**Comment by ramasilveyra** [comment]
But, in this way finish the task when maybe del isn't done yet? :confused:

**Comment by sindresorhus** [comment]
No, you now return a promise from `del` and gulp waits for that to resolve or reject.

**Comment by adambuczynski** [comment]
I'm using it this way (with gulp 4) and the task is run in series, e.g.:

```javascript
function clean() {
  return del(destination);
}

gulp.task('build', gulp.series(
  clean,
  gulp.parallel(
    buildStatic,
    buildAppJs, buildAppScss,
    buildVendorJs, buildVendorCss
  ),
  buildIndex
));
gulp.task('default', gulp.series(
  gulp.parallel('lint', 'test'), 'build', gulp.parallel('watch', 'start')
));
```

However, since I adopted this new API I keep getting the following error when I first run the task (running it a second time after it causes no problems):

```
[11:01:27] Starting 'clean'...
[11:01:27] 'clean' errored after 37 ms
[11:01:27] Error: ENOTEMPTY: directory not empty, rmdir '/Users/Adam/Sites/some-site/public'
  at Error (native)
```

Any thoughts? Needless to say that the test & lint tasks don't interact with the public folder at all, so I'm not sure why this error is thrown.

**Comment by adambuczynski** [comment]
It seems the cause was that some hidden files were being created and, subsequently, not deleted, as I didn't use the option `dot: true`.

However, it remains odd that when running the command for a second time didn't cause the same error. You'd think the hidden files would still be there.

**Comment by adambuczynski** [comment]
Correction, it's still happening, even with the `dot: true` parameter. Any thoughts as to what could be wrong?

**Comment by adambuczynski** [comment]
It looks like the culprit is a .DS_Store file. Perhaps it's being re-created in the folder due to something Gulp does? Is there a way to fix this issue from within del?

**Comment by schnittstabil** [comment]
`.DS_Store` are created by Finder; seems not related to `del`.

**Comment by adambuczynski** [comment]
I know they are created by Finder, but the question is *why* are they created by Finder when `del` is in the process of deleting the folder, and why is `del` crashing because of it?

**Comment by schnittstabil** [comment]
@adambuczynski It is not possible to remove a non-empty folder, we need to remove its contents first. 
As `del` does not trigger the recreation – by a system call or similar – I do not see what we could do better. 
Have you tried to close all Finder instances before you start `del`?

**Comment by adambuczynski** [comment]
I will try to see if that was causing the issue. However, I do not recall having this issue before though, when I was using del with a callback instead of via the promise interface, so I thought it might have to do with that. I will do some more extensive testing.

**Comment by adambuczynski** [comment]
Have retested several times today but did not manage to reproduce anymore. I did have a lot of Finder windows open yesterday, so that may have been the cause. I've tested with two open windows now, each showing the relevant folder, but it didn't seem to cause any issues anymore. If I encounter it again I will report back with further information.
