### ISSUE TITLE
No support for finally?

### ISSUE THREAD

**Issue by adambuczynski** [sindresorhus/del#49]
Got the following error:

`TypeError: del(...).catch(...).finally is not a function`

Given `del` has a promise interface, is there no support for a `finally` clause?

**Comment by SamVerschueren** [comment]
`.finally` isn't part of the spec.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

You can use `.catch(...).then(...)`. Think that is the same behaviour.

**Comment by adambuczynski** [comment]
Yup just noticed it myself! How strange.

**Comment by SamVerschueren** [comment]
Why is it strange :)? I think `finally` was never part of the spec but was added by libraries like `Q` or `BlueBird`.

**Comment by kevva** [comment]
They discussed it but it didn't make it into ES2015. It might make it into ES2016 though. Read https://esdiscuss.org/topic/why-the-ecmascript-2015-promises-don-t-have-finally-methods and https://esdiscuss.org/topic/proposal-promise-prototype-finally.

**Comment by adambuczynski** [comment]
@SamVerschueren I just found it curious, because every single library and framework that I've used that uses promises (Angular, Ember, Q, etc) had a `finally` implementation. This is the first time I've seen an implementation that doesn't have it.

Thanks for the info @kevva !

**Comment by SamVerschueren** [comment]
@kevva Thanks for the info!

@adambuczynski Angular's [`$q`](https://docs.angularjs.org/api/ng/service/$q) is based upon `Q` which has a `finally` method. All Sindre's modules are based upon the native node (>= 0.12) Promise (which doesn't have `finally` or upon [pinkie](https://www.npmjs.com/package/pinkie) which is a polyfill based on the spec.

**Comment by FaiChou** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

chrome63 supportted

**Comment by adamreisnz** [comment]
Yes, it's (coming in Node 10)[http://node.green/#ESNEXT-candidate--stage-3--Promise-prototype-finally].
