### ISSUE TITLE
File has no permission entries, del returns exit code 0 / success

### ISSUE THREAD

**Issue by mspace** [sindresorhus/del#50]
I'm using del to delete file like this (and in some cases directories *.css)

``` javascript
gulp.task("delete", function(cb) {
  del(["./deleteMe.txt"]).then(function (paths) { // returns a promise; https://github.com/sindresorhus/del
    console.log("Deleted files and folders: \n", paths.join('\n'));
    cb();
  }, function (reason) {
    cb("Failed to delete files " + reason);
  });
});
```

> [08:55:51] Using gulpfile X:\Gulpfile.js
> [08:55:51] Starting 'delete'...
> [08:55:51] Finished 'delete' after 3.82 ms
> Process terminated with code 0.
> Deleted files and folders: 

If the same task uses nodejs's fs it works, it reports error correctly:

``` javascript
fs.unlink("deleteMe.txt", function (reason) {
    console.log("Reason " + reason);
  });
```

> Reason Error: EPERM: operation not permitted, unlink 'X:\deleteMe.txt'

deleteMe.txt permissions:

![file_permissions](https://cloud.githubusercontent.com/assets/1265588/12575358/199bc56e-c40c-11e5-9c24-6784ae1344c9.png)

**Comment by SamVerschueren** [comment]
Try returning the promise in the gulp task

```js
gulp.task("delete", function() {
  return del(["./deleteMe.txt"]).then(function (paths) { // returns a promise; https://github.com/sindresorhus/del
    console.log("Deleted files and folders: \n", paths.join('\n'));
    cb();
  }, function (reason) {
    cb("Failed to delete files " + reason);
  });
});
```

**Comment by mspace** [comment]
Callback must be provided as a function argument. I believe there are two ways:

```javascript
gulp.task("delete", function() {
  return del(["./deleteMe.txt"]
});
```

or with a callback

```javascript
gulp.task("delete", function(cb) {
  del(["./deleteMe.txt"]).then(function (paths) {
    cb(); // ok
  }, function (reason) {
    cb("Failed to delete files " + reason); // fail
  });
});
```

**Comment by SamVerschueren** [comment]
Oh, didn't notice the `cb`. A gulp task can handle a promise so your first example should work and should return an error.

Tested on Mac OSX

```js
'use strict';

const gulp = require('gulp');
const del = require('del');

gulp.task('delete', () => {
    return del('./deleteMe.txt');
});
```

output

```
[09:35:24] Starting 'delete'...
[09:35:24] 'delete' errored after 8.21 ms
[09:35:24] Error: EPERM: operation not permitted, unlink '/Users/sam/Projects/playground/gulp-test/deleteMe.txt'
    at Error (native)
```

**Comment by mspace** [comment]
Tested your code, but on Windows 10 still no error. 

```
[09:41:02] Using gulpfile X:\Gulpfile.js
[09:41:03] Starting 'delete'...
[09:41:03] Finished 'delete' after 5.92 ms
Process terminated with code 0.
```

**Comment by schnittstabil** [comment]
@mspace Does `del` delete your `"./deleteMe.txt"`? – at least on Linux it is possible to delete a file w/o permissions; you only need the permission of the folder…

**Comment by mspace** [comment]
@schnittstabil No, file stays on the filesystem. It does not get deleted. Permissions on the folder are set ok: full control modify, read & execute, list folder contents, read, write for currently logged-in user in this case me.

**Comment by schnittstabil** [comment]
Thanks for reporting this, that is a rimraf issue: isaacs/node-glob/issues/245

**Comment by datatypevoid** [comment]
I can also confirm this issue on Windows 10 64-bit with node 5.5.0 and npm 3.3.12. No matter what I do I cannot delete even the simplest directory with something like:

    gulp.task('clean:docs', function () {
      return del([
        // here we use a globbing pattern to match everything inside the `docs` folder
        './docs/**/*'
      ]);
    });

**Comment by schnittstabil** [comment]
@datatypevoid 
> even the simplest directory

That seems not related to this issue, you may try:

```js
gulp.task('clean:docs', function () {
  console.log('current directory: ', require('process').cwd());
  console.log('files:', globby.sync(['./docs/**/*']));
  return del(['./docs/**/*']);
});
```

**Comment by datatypevoid** [comment]
Sorry I was still recovering this morning when I wrote that, and I must admit I was half-reading the thread trying to get in the door. When I use that function, I get:

    current directory: f:\sites\project-name-here
    files: []

but the files and directories remain unaffected.

**Comment by schnittstabil** [comment]
@datatypevoid If `f:\sites\project-name-here\docs` exists, then it looks like a [globby](https://github.com/sindresorhus/globby) issue. Please open a new issue there.

**Comment by datatypevoid** [comment]
Sorry for my ignorance man. Thanks for your help though!

**Comment by sindresorhus** [comment]
Closing as isaacs/node-glob#245 was fixed.
