### ISSUE TITLE
Negating doesn't prevent deletion of the parent folder

### ISSUE THREAD

**Issue by adamk22** [sindresorhus/del#53]
For a project that I'm working on I used the following dir structure:

```
Parent Folder
All build files go here
- gulp (gulp file/content)
- src (working dir)
```

And I have the following build:cleanfolder task:

```
gulp.task('build:cleanfolder', function() {
    del([
        '!ParentFolder',
        '!../',
        '!../gulp',
        '!../src',
        '../**'
        ], {force: true});
});
```

So what I want is that whenever I run the build task, it empties the parentfolder ignoring the gulp, src maps and the parent folder. However, what happens is that it completely deletes the parent folder incl. its subfolders even though I negated both '../' and the Parent Folder. 

Am I missing something obvious or is this a known issue (or am I just using it the wrong way)

**Comment by SamVerschueren** [comment]
Place the whitelist pattern first `../**`

**Comment by adamk22** [comment]
I've tried that without success unfortunately

**Comment by schnittstabil** [comment]
@adamk22 You may wanna try:
```js
gulp.task('build:cleanfolder', function() {
  return del([
        '../**',
        '!..',               // i.e. '../../ParentFolder'; Note: no trailing '/'!
        '!../gulp/**',       // exclude gulp and everything within
        '!../src/**',        // exclude src and everything within
        ], {
            force: true,
            dryRun: true  // just for debugging
        }
  ).then(console.log);  // just for debugging
});
```

**Comment by adamk22** [comment]
Yes! This is it! Thank you so much
