### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by Avcajaraville** [sindresorhus/del#54]
I just run the tests and they are failing; wondering why do we have code not passing the tests on master.

Only 3 tests are passed:
![captura de pantalla 2016-04-07 a las 10 13 40](https://cloud.githubusercontent.com/assets/2271201/14344731/b3b1f422-fca9-11e5-9d8e-decff4448450.png)

Not sure if you were aware of this issue. Sorry if you are and prefer me not to fill an issue.

**Comment by SamVerschueren** [comment]
reinstall AVA (v0.14)

**Comment by Avcajaraville** [comment]
Just tried, still, one test is failing:

![captura de pantalla 2016-04-07 a las 10 49 25](https://cloud.githubusercontent.com/assets/2271201/14345653/7bdd7008-fcae-11e5-84e1-d7e66bb78de3.png)

**Comment by sindresorhus** [comment]
Yes, I'm aware. I was working through fixing tests.
