### ISSUE TITLE
del.sync() returns error but promisified del() does not

### ISSUE THREAD

**Issue by rogierschouten** [sindresorhus/del#55]
While trying to delete a directory with in-use files on Windows 10,  del.sync() produced the error "Directory not empty"  but running del().then(function, function) did not return an error in the second then() function.

**Comment by SamVerschueren** [comment]
And does it do something with a `catch` function? It should be the same though, but you never know.

**Comment by rogierschouten** [comment]
OK this is weird. Some data points on this issue:

```javascript
var del = require("del");
var gulp = require("gulp");

gulp.task("clean", function() {
	return del([	"some_glob_leading_to_error"]);
});
```

No errors are printed, process stops.  However, check this:

```javascript
var del = require("del");
var gulp = require("gulp");
var util = require("util");

gulp.task("clean", function() {
	return del([	"some_glob_leading_to_error"]);
});

process.on("exit", function(exitcode) {
   console.log(util.inspect(gulp.tasks["clean"]));
});
```

This prints:

```shell
{ fn: [Function],
  dep: [ 'document_clean' ],
  name: 'clean',
  args:
   { task: 'clean',
     message: 'clean promise',
     duration: 5.95151387,
     hrDuration: [ 5, 951513870 ],
     err:
      { [Error: EBUSY: resource busy or locked, rmdir 'C:\some_dir']
        errno: -4082,
        code: 'EBUSY',
        syscall: 'rmdir',
        path: 'C:\\some_dir' } },
  running: false,
  duration: 5.95151387,
  hrDuration: [ 5, 951513870 ],
  done: true }

```


So, gulp apparently does get the error and doesn't print it. Time for some generic tests with promises:

```
var gulp = require("gulp");
var Promise = require("bluebird");

gulp.task("clean", function() {
	return Promise.reject(new Error("foo"));
});
```

Gulp nicely prints the error "foo".


This is with gulp 3.9.1.

So gulp can handle promises and del returns an error and somehow it doesn't work together.

**Comment by sholladay** [comment]
What happens if you use Gulp 4? `npm install gulpjs/gulp#4.0`
