### ISSUE TITLE
Case sensitivity on macOS

### ISSUE THREAD

**Issue by qbolec** [sindresorhus/del#62]
There are file systems which are not case sensitive.
This is problematic in a scenario, where I know that my application created file.txt in `sub/dir`, but I do not know if `sub/dir` is named `sub/dir` or `Sub/Dir` or `sub/Dir` or what.
To prevent `sub/dir/file.txt` from being removed I need not only:
```
[
 'sub/**',
 '!sub/dir/file.txt',
 '!sub/dir',
 '!sub',
]
```
but also all variants of `sub`, `Sub`, `SUB`, `sUB`. 
It would be great to be able to pass 'case sensitivity' flag somewhere.

**Comment by qbolec** [comment]
I've tracked it down to this issue: https://github.com/isaacs/node-glob/issues/343

**Comment by schnittstabil** [comment]
All options are forwarded to `node-glob` (via  [`globby`](https://github.com/sindresorhus/globby)) – except `force` and `dryRun` ofc. For this reason I'm closing this issue, fixing it in `del` does not make sense.
