### ISSUE TITLE
Consider bumping `globby`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [sindresorhus/del#63]
`globby@7` comes with two new options: `expandDirectories` and `gitignore`.  It would be nice to be able to use those from `del`.  One potential problem I see with this proposal is that `globby@7` now has `nodir` default to true, which may not be what is expected in the use cases for `del`.

**Comment by odarbelaeze** [comment]
Was about to do the same 👍

**Comment by sindresorhus** [comment]
@evilebottnawi If prefer not to do that yet. Globby still has many regressions because of the switch to `fast-glob`: https://github.com/sindresorhus/globby/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
