### ISSUE TITLE
Requests confirmation when deleting folder contents

### ISSUE THREAD

**Issue by kibertoad** [sindresorhus/del#65]
Windows 10, del v 3.0.0, del-cli v 1.1.0

When used in an npm script like this:

del \"app/typings/models\"

_del_ requires "Are you sure" confirmation. This makes it entirely unsuitable for usage in CI.

Would it be possible to add option switch that would silently confirm on any prompts?

**Comment by kibertoad** [comment]
This might be a windows-only version - it seems that adding /Q key resolves the issue, but having it in a script breaks cross-platform compatibility. Would be extremely awesome if _del_ implemented a cross-platform-friendly option that would add platform-specific options to call when necessary.

**Comment by sindresorhus** [comment]
Wrong repo. I think you meant to open it on https://github.com/sindresorhus/del-cli

`del` doesn't ask for confirmation, so it's clear you're using the native `del` instead of `del-cli`. Please read the instructions in the readme: https://github.com/sindresorhus/del-cli#usage

**Comment by kibertoad** [comment]
Missed the part that I was supposed to use del-cli explicitly. Thanks a lot, this solved it!
