### ISSUE TITLE
dependency not capatible with 10+

### ISSUE THREAD

**Issue by dkebler** [sindresorhus/del#67]
keeping up with the jones here looks like upath version is not 10+ compatible.
upath (1.1.0) has been fixed for 10 but at least one of your dependencies hasn't upgraded. 
https://github.com/anodynos/upath/issues/21

```
ya del
yarn add v1.6.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
```

**Comment by gluons** [comment]
`del` doesn't have `upath` in any dependencies.  
My repo also has `del`. I can't find `upath` in `yarn list`.  
[See proof in visualization](https://npm.anvaka.com/#/view/2d/del)

Or try to find `upath` in your `yarn.lock` file.
