### ISSUE TITLE
Sometimes error "EINVAL" when removing files in macOS temp directory

### ISSUE THREAD

**Issue by chrisblossom** [sindresorhus/del#68]
Sometimes when deleting a folder that has nested folders/files inside the macOS temp directory, error `EINVAL` is thrown. This is not happening when using `.sync`.

Minimal example repo: https://github.com/chrisblossom/del-issue-68

```
{ Error: EINVAL: invalid argument, rmdir '/var/folders/hm/n_tq5p6j7j313n28pjzvk63c0000gn/T/del-issue-68/a/b/c'
  errno: -22,
  code: 'EINVAL',
  syscall: 'rmdir',
  path: '/var/folders/hm/n_tq5p6j7j313n28pjzvk63c0000gn/T/del-issue-68/a/b/c' }
```

```
  System:
    OS: macOS High Sierra 10.13.3
    CPU: x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  Binaries:
    Node: 8.11.2 - ~/.nvm/versions/node/v8.11.2/bin/node
    Yarn: 1.7.0 - ~/.yarn/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.2/bin/npm
```

**Comment by saunders99999** [comment]
We saw the same problem on macOS, but found a patch that seems to work on node6, 8.  This is both with and without the del 'force' option.

(root/dist/folder1 represents absolute path)
root/dist/folder1
root/dist/folder2

**Original globs with the issue**
```
return del([
	root/dist/folder1/**,
	root/dist/folder2/**
]
```

**Patch, remove trailing \*\*, seem to work.**
```
return del([
	root/dist/folder1,
	root/dist/folder2
]
```

The issue still needs fixed, but thought this may help others.

**Comment by nathanjd** [comment]
This sometimes happens to me even outside of the temp directory. Though I have yet to find a guaranteed repro case, it reproduces intermittently fairly easily.

```
Error: EINVAL: invalid argument, rmdir '/Users/q4i2/Projects/web-perf/device-profiling-service/dev-ops/output/aggregate-trigger-lamdba-1.3.1/package/node_modules/@nui'
```

Glob used was `del("/Users/q4i2/Projects/web-perf/device-profiling-service/dev-ops/output/**/*")`

Node v8.15.0
NPM 6.9.0
OS X 10.13.6 (17G5019)

**Comment by bytestream** [comment]
Just ran into this on Mac. Based on rimraf docs, `del()` is async and `del.sync` is synchronous and I guess an array of globs is causing a race condition when using async.

`del.sync` fixed it anyway.

**Comment by chrisblossom** [comment]
For future reference, this is how I've solved this issue for my projects:

```js
// del.js

const delActual = require('del');

function sleep(ms) {
  return new Promise(resolve => {
    setTimeout(resolve, ms);
  });
}

async function del(patterns, options) {
  try {
    const removed = await delActual(patterns, options);

    return removed;
  } catch (error) {
    /**
     * Intermittently error code 'EINVAL' is being thrown here.
     * Would be great to find out why
     * Test will fail only if validating removed files.
     * Retry twice with 100ms between each try
     */
    if (error.code === "EINVAL") {
      await sleep(100);

      try {
        const removed = await delActual(patterns, options);

        return removed;
      } catch (error2) {
        await sleep(100);

        if (error2.code === "EINVAL") {
          // Will throw 'EINVAL' if it happens a third time
          const removed = await delActual(patterns, options);

          return removed;
        }

        throw error2;
      }
    }

    throw error;
  }
}

// EINVAL does not happen async
del.sync = DelSync;

module.exports = del;
```
