### ISSUE TITLE
Does the module work with gulp 4?

### ISSUE THREAD

**Issue by Alecto** [sindresorhus/del#71]
task deletes files:

gulp.task('clear-min-js', function() {
  return del.sync(path.jsFolder + '**/*.min.js');
});

but in gulp 4 it doesn't work:

[16:49:51] Starting 'clear-min-js'...
[16:49:51] The following tasks did not complete: clear-min-js
[16:49:51] Did you forget to signal async completion?

Process finished with exit code 1

where is the mistake? How to make the code work?

**Comment by sindresorhus** [comment]
Remove the `.sync` part. Use the Gulp issue tracker for Gulp support questions.

**Comment by Alecto** [comment]
thanks
