### ISSUE TITLE
Deletes nothing

### ISSUE THREAD

**Issue by warpdesign** [sindresorhus/del#72]
I have a directory with the following folders:
foo/
bar/

Runing this code:

```
const del = require('del');

del(["./foo"])
.then(() => {
    console.log('yeah');
})
.catch((err) => {
    console.log('oops', err);
});
```

outputs `yeah` but the directory `foo` isn't deleted.

I tried replacing `./foo` with `./foo/**` but the result was the same.

Also, trying to remove a non-existing folder also resolves the promise.

I am running node `8.11.4` and del `3.0.0`. I tried on Windows 10 & Linux with the same results.

**Comment by warpdesign** [comment]
The weird thing is that using the `del-cli` package and typing `del-cli foo` works as expected.

But creating a file with the above code and typing `node file.js` won't work.

**Comment by deadcoder0904** [comment]
@warpdesign it works for me on a Mac. My version is `5.1.0`. It even works if it has a file inside it. I copy-pasted your same code. Here's a GIF in action 👇

![del-screencast](https://user-images.githubusercontent.com/16436270/65833686-6d94af80-e2f0-11e9-87fb-47cdea54fc09.gif)

**Comment by kevva** [comment]
@warpdesign, could you try a newer version? `v3.0.0` is over two years old.

**Comment by warpdesign** [comment]
I can't reproduce it anymore: closing it.
