### ISSUE TITLE
Rollback Deletion

### ISSUE THREAD

**Issue by ethikz** [sindresorhus/del#73]
I tried looking through the docs and issues and couldn't find anything about it but what I'm wondering if there is some sort of api for rolling back the deletion.

Reason I ask is because let's say I have this as a flow:

I clean the `dist` initially then try to build my files and at some point in the flow, a build task fails, I'd like for it to restore the previous `dist` folder and not leave it blank.

**Comment by sindresorhus** [comment]
There's no going back. This is a permanent deletion. If you want to be able to restore, you should use [`trash`](https://github.com/sindresorhus/trash) instead.

**Comment by ethikz** [comment]
Hmm looking at trash that is more than what I need.  I basically need to store the previous `dist` folder in a temp folder and if all tasks pass then delete the `tmp` folder but if not, it needs to replace the broken `dist` folder
