### ISSUE TITLE
Delete empty dirs with excluded node_modules

### ISSUE THREAD

**Issue by whitecolor** [sindresorhus/del#76]
I'm using such code to remove all the files except `node_modules` folders.

```js
del([`${folder}/**/*`, '!**/node_modules/**'], {
    dot: true,
    nodir: true
  })
```

It works fine, but the small problem - it leaves empty directories without files. If set `nodir: false` then it will also deletes `node_modules` despite the negate pattern.

Is there a solution to this problem?

**Comment by InsanityMeetsHH** [comment]
You need two excludes.
Exclude folder: `'!**/node_modules`
Exclude files in folder: `!**/node_modules/**/*`

**Comment by whitecolor** [comment]
@InsanityMeetsHH not this doesn't work
```
del([`${folder}/**/*`, '!**/node_modules', '!**/node_modules/**/*'], {
    dot: true,    
  })
```
removes all the files and folders.

**Comment by viT-1** [comment]
Confirm: empty dirs not deleted. I tried nodir:true & nodir:false same effect =(
