### ISSUE TITLE
Parent Directory Deleted even with !parent directory included in array

### ISSUE THREAD

**Issue by oleersoy** [sindresorhus/del#79]
First of all thanks for creating del.  It's awesome!  

I'm doing this:

```
const SANDBOX = 'test/sandbox/';
del.sync([path.join(SANDBOX, '**'), `!${SANDBOX}`]);
```

This still deletes the `sandbox` parent directory, even though `!${SANDBOX}` is included in the argument array.

Would it be possible to adopt the convention where if the path includes `/` at the end of the path, then don't delete the parent directory?  So in other words:

If `/test/sandbox/` then don't delete the `sandbox` directory, but if `/test/sandbox` then do delete the `sandbox` directory?

**Comment by chrisblossom** [comment]
Try this instead:
```js
const SANDBOX = 'test/sandbox/';
del.sync([path.join(SANDBOX, '**/*')]);
```
