### ISSUE TITLE
Typescript error for glob types in v4

### ISSUE THREAD

**Issue by vladshcherbin** [sindresorhus/del#83]
Hey,

Since v4 has types file inside, there is no `glob` types which is used inside.

When using v4 typescript gives you an error about this missing types. v3 had external types which installed `glob` types automatically and didn't give you an error.

**Comment by sindresorhus** [comment]
Is this still a problem with v4.1.0? Ensure you use it like done here: https://github.com/sindresorhus/del/blob/master/index.test-d.ts

**Comment by vladshcherbin** [comment]
@sindresorhus yes, this also exists in 4.1.0

It happens because glob options are imported [here](https://github.com/sindresorhus/del/blob/v4.1.0/index.d.ts#L1), but glob itself doesn't have types inside, they have to be installed separately using `@types/glob`.

In v3, types were installed using `@types/del` which had a `@types/glob` dependency and installed types for you automatically.

So, can think of 2 ways of solving this:

1) add `@types/glob` to dependencies of this package. This will install needed types automatically, but will install unnecessary types for non-TS devs.
2) move back to using `@types/del`. Using it will install glob types automatically and won't pollute non-TS devs dependencies.

I had same issue and conclusion after trying to add types to one of my packages. Chose 2-nd way since it doesn't add unnecessary type packages for non-TS devs. I guess, this is one of the reasons why `@types` repo is so popular and suggested in [ts docs](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) for non-ts package.

Hope this makes sense :)

**Comment by sindresorhus** [comment]
Thanks for elaborating :)

**Comment by BendingBender** [comment]
Ups, my bad!

**Comment by sindresorhus** [comment]
@BendingBender No worries. I missed it too. `tsd` should have caught it though... https://github.com/SamVerschueren/tsd/issues/24
