### ISSUE TITLE
Dependence on @types/glob pollutes and breaks almost all client-side projects

### ISSUE THREAD

**Issue by falsandtru** [sindresorhus/del#88]
As https://travis-ci.org/falsandtru/pjax-api/jobs/525654172#L485.

This is caused by the dependence on @types/node (https://github.com/sindresorhus/del/commit/0361dccad6cd8b0b0f02589a26b021f9438f4b91). See the histories:

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/22510
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22528

**Comment by sindresorhus** [comment]
`del` is a Node.js module, so obviously it needs `@types/node`. If there are any incompatibilities or problems, you should rather bring those concerns to https://github.com/DefinitelyTyped/DefinitelyTyped or https://github.com/Microsoft/TypeScript.

**Comment by falsandtru** [comment]
Your answer ought to be right but since your change made a real problem you should revert the change. I think this is a bug of TypeScript but we can't avoid this upstream problem easily. So you shouldn't bundle type definitions until TypeScript resolves this problem. Distributing type definitions via @types has no problem. You should use it.

https://github.com/Microsoft/TypeScript/issues/31148

**Comment by Sebazzz** [comment]
I agree. When you need it you can include `@types/node` manually if required.

Anyway, for anyone running into this issue, and using yarn (which you should anyway), create a `.yarnclean` file and put in the following content:

```
@types/node
@types/glob
```

This deletes the types and prevent Typescript from picking them up.
